netinfluence_secure_display:
    path:     /netinfluence_secure_display
    defaults: { _controller: "NetinfluenceSecureDisplayBundle:Display:decrypt" }
    requirements:
        methods:  POST
    options:
        expose: true
