services:
    Netinfluence\SecureDisplayBundle\Twig\SecureDisplayExtension:
        class: Netinfluence\SecureDisplayBundle\Twig\SecureDisplayExtension
        public: true
        arguments:
            - "@Netinfluence\SecureDisplayBundle\Services\Encrypter"
            - "%netinfluence_secure_display.template%"
        tags:
            - { name: twig.extension }
    Netinfluence\SecureDisplayBundle\Services\Encrypter:
        class: Netinfluence\SecureDisplayBundle\Services\Encrypter
        public: false
        arguments:
            - "@session"
            - "%netinfluence_secure_display.key%"
