services:
    netinfluence.twig.secure_display_extension:
        class: Netinfluence\SecureDisplayBundle\Twig\SecureDisplayExtension
        arguments:
            - "@encrypter"
        tags:
            - { name: twig.extension }
    encrypter:
        class: Netinfluence\SecureDisplayBundle\Services\Encrypter
        arguments:
            - "%netinfluence_secure_display.key%"
